### ISSUE TITLE
UI Basic

### ISSUE THREAD

**Issue by Carrillola** [vcu-cmsc355-f17/android-app-mu-sometimes-1#2]

**Comment by shresthas22** [comment]
![scan_0001-1](https://user-images.githubusercontent.com/32022715/30998647-4355f428-a49e-11e7-8ba6-a4aed2c90a5b.png)
![scan_0002-1](https://user-images.githubusercontent.com/32022715/30998650-44db1eea-a49e-11e7-84af-578ec6ecea8f.png)
![scan_0003-1](https://user-images.githubusercontent.com/32022715/30998651-4675cf98-a49e-11e7-9963-a2dbcf5bc263.png)
